### ISSUE TITLE
관련 프로젝트에 관하여

### ISSUE THREAD

**Issue by zs0057** [Ssuhyeong/Cloud-Cover-Monitor#1]
안녕하세요 해당 프로젝트를 맡게된 컴퓨터공학부(현 컴퓨터인공지능학부) 3학년 19학번 김지성입니다.
혹시 해당 프로젝트에 관하여 여쭈어 보고싶은게 있는데 메일주소를 알 수 있을까요?

**Comment by Ssuhyeong** [comment]
네 ***@***.*** 입니다

2023년 4월 10일 (월) 오후 8:54, zszszszs ***@***.***>님이 작성:

**Comment by zs0057** [comment]
혹시 메일이 ***@***.***이렇게 출력되는데 제메일로 다시 보내주실 수 있나요?
제 메일은 soss0527@naver.com 입니다.

**Comment by Ssuhyeong** [comment]
아 제가 모바일로 전송해서 오류가 발생한 것 같아요
tngud124@kakao.com 제 이메일입니다.
